env:
  browser: true
  es6: true
extends: 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 11
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  # "prefer-const": false,
  # "no-trailing-whitespace": false,
  # "whitespace": false
}
   

